# -*- coding: utf-8 -*-
# vim: ft=yaml
---
## Machine config
os: windows
language: c

## Script to run for the test stage
script:
  - winrm get winrm/config
  - netstat -anp TCP
  - powershell -Command ". {Invoke-Command -ComputerName 'localhost' -ScriptBlock {$env:COMPUTERNAME} }"

