# -*- coding: utf-8 -*-
# vim: ft=yaml
---
## Machine config
os: windows
language: shell

## Script to run for the test stage
script:
  - powershell -Command '. {echo $env:PATH}'
  - net user; net user travis
  - powershell -command "net user /add test_user Pass@word1; net localgroup administrators test_user /add"
  - net user test_user
  - netstat -anp TCP
#  - winrm.cmd set winrm/config/client '@{TrustedHosts="*"}'
  - winrm.cmd set winrm/config/service '@{AllowUnencrypted="true"}'
  - winrm.cmd get winrm/config
  - |
    powershell -Command '. {
    $password = ConvertTo-SecureString "Pass@word1" -AsPlainText -Force
    $psCred = New-Object System.Management.Automation.PSCredential -ArgumentList ("test_user", $password)
    Invoke-Command -ComputerName localhost -ScriptBlock { 1 } -Credential $psCred
    }'
