# -*- coding: utf-8 -*-
# vim: ft=yaml
---
## Machine config
os: windows
language: shell

## Script to run for the test stage
script:
  - powershell -Command '. {echo $env:PATH}'
  - net user; net user travis
  - powershell -command "net user /add test_user Pass@word1; net localgroup administrators test_user /add"
  - net user test_user
  - netstat -anp TCP
  - winrm.cmd get winrm/config
  - |
    powershell -Command '. {echo "line 1"
    echo "line 2" }'
  - powershell -Command '. {Invoke-Command -ComputerName "localhost" -ScriptBlock {$env:COMPUTERNAME} }'

