# -*- coding: utf-8 -*-
# vim: ft=yaml
---
## Machine config
os: windows
language: shell

## Script to run for the test stage
script:
  - powershell -Command ". {echo $env:PATH}"
  - netstat -anp TCP
  - powershell -Command ". {winrm get winrm/config}"
  - powershell -Command ". {Invoke-Command -ComputerName 'localhost' -ScriptBlock {$env:COMPUTERNAME} }"

