# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

env:
  machine_user: test_user
  machine_pass: Pass@word1
  machine_port: 5985
  KITCHEN_LOCAL_YAML: .kitchen.github.yml
  SSL_CERT_FILE: c:\projects\kitchen-machine\certs.pem
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: whoami; net user runneradmin
    - run: net user /add $env:machine_user $env:machine_pass
    - run: net localgroup administrators $env:machine_user /add
    - run: gem install bundler --quiet --no-ri --no-rdoc
    - run: Invoke-WebRequest -Uri http://curl.haxx.se/ca/cacert.pem -OutFile c:\projects\kitchen-machine\certs.pem

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
